version: '3.0'

services:
   springBoot:
     build: ./my-apps/springboot
     image: springboot:tag
     ports:
       - "8006:8080"
     restart: always 
     depends_on:
      - db
     networks:
      - mysql
   angular:
     build: ./my-apps/angular
     image: angular:tag
     ports:
       - "8007:80"
     restart: always
   db:
     image: mysql:5.7
     command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
     volumes:
       - ./my-apps/mysql/init:/docker-entrypoint-initdb.d
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       #MYSQL_DATABASE: wordpress
       #MYSQL_USER: wordpress
       #MYSQL_PASSWORD: wordpress
     networks:
      - mysql
   wordpress:
     image: wordpress:latest
     ports:
       - "8005:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
      - mysql
     depends_on:
      - db
volumes:
    db_data:
networks:
    mysql: